version: "3.7"

services:
  case-flow-web:
    container_name: case-flow-web
    build:
      context: .
      dockerfile: dev_Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
        - REACT_APP_KEYCLOAK_CLIENT=${REACT_APP_KEYCLOAK_WEB_CLIENTID:-case-flow-web}
        - REACT_APP_KEYCLOAK_URL_REALM=${REACT_APP_KEYCLOAK_URL_REALM:-caseflow}
        - REACT_APP_KEYCLOAK_URL=${REACT_APP_KEYCLOAK_URL}
        - REACT_APP_APPLICATION_NAME=${APPLICATION_NAME:-caseflow.ai}
        - REACT_APP_CASEFLOW_API_URL=${REACT_APP_CASEFLOW_API_URL}
        - REACT_APP_CASEFLOW_GRAPHQL_API_URL=${REACT_APP_CASEFLOW_GRAPHQL_API_URL}
        - REACT_APP_CASEFLOW_DMS=${REACT_APP_CASEFLOW_DMS}
        - REACT_APP_CASEFLOW_LOB_GRAPHQL_API_URL=${REACT_APP_CASEFLOW_LOB_GRAPHQL_API_URL}
        - REACT_APP_PAGINATION_TAKE=${REACT_APP_PAGINATION_TAKE}
        - REACT_APP_FORMSFLOW_URL=${REACT_APP_FORMSFLOW_URL}
        - REACT_APP_FORMSFLOW_APP_URL=${REACT_APP_FORMSFLOW_APP_URL}

        
       
    ports:
      - "3000:3000"
    tty: true
