version: "3.7"

services:
  case-flow-core:
    container_name: case-flow-core
    build: .
    environment:
        - NODE_ENV=${NODE_ENV:-production}
        - KEYCLOCK_CLIENT_ID=${KEYCLOCK_CLIENT_ID}
        - KEYCLOCK_REALM=${KEYCLOCK_REALM}
        - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
        - KEYCLOCK_AUTH_URL=${KEYCLOCK_AUTH_URL}
        - KEYCLOCK_SECRET=${KEYCLOCK_SECRET}

        - POSTGRESQL_HOST=${POSTGRESQL_HOST}
        - POSTGRESQL_PORT=${POSTGRESQL_PORT}
        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        - POSTGRES_DB_USERNAME=${POSTGRES_DB_USERNAME}
        - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}

        

       


    ports:
      - "7001:7001"
    tty: true
